name: InfiniteClaims
main: hskrasek.InfiniteClaims.InfiniteClaims
author: hskrasek
description: InfiniteClaims is a plugin designed for the InfinitePlots world generator to manage the plot allocation via WorldGuard. Originally coded by Toffer, rebuilt by Sekonda and hskrasek.
version: 2.0.0
depend: [InfinitePlots, WorldGuard, WorldEdit]
commands:
   iclaims:
      description: InfiniteClaims base command.
      usage: /<command>
   iclaimsplot:
      description: Teleport to own plot, or someone elses.